import { AcademicResource, Lang } from "@/lib/types/dataTypes";

export const ACADEMIC_RESOURCES: Lang<AcademicResource> = {
  es: [
    { resourceId: "resource_1", resourceName: "Planificación de clases" },
    { resourceId: "resource_2", resourceName: "Guias de lección" },
    { resourceId: "resource_3", resourceName: "Tarjetas de discución" },
    { resourceId: "resource_4", resourceName: "Preguntas de evaluación" },
    { resourceId: "resource_5", resourceName: "Tareas para el estudiante" },
    { resourceId: "resource_6", resourceName: "Lecturas relacionadas" },
    { resourceId: "resource_7", resourceName: "Diapositivas/presentación" },
    { resourceId: "resource_8", resourceName: "Handouts" },
    { resourceId: "resource_9", resourceName: "Bibliografía - referencias" },
    { resourceId: "resource_10", resourceName: "Syllabus" },
    { resourceId: "resource_11", resourceName: "Lecturas" },
    { resourceId: "resource_12", resourceName: "Otro" },
  ],
  en: [
    { resourceId: "resource_1", resourceName: "Lesson Planning" },
    { resourceId: "resource_2", resourceName: "Lesson Guides" },
    { resourceId: "resource_3", resourceName: "Discussion cards" },
    { resourceId: "resource_4", resourceName: "Evaluation questions" },
    { resourceId: "resource_5", resourceName: "Student assignments" },
    { resourceId: "resource_6", resourceName: "Related readings" },
    { resourceId: "resource_7", resourceName: "Slides/presentation" },
    { resourceId: "resource_8", resourceName: "Handouts" },
    { resourceId: "resource_9", resourceName: "Bibliography - references" },
    { resourceId: "resource_10", resourceName: "Syllabus" },
    { resourceId: "resource_11", resourceName: "Readings" },
    { resourceId: "resource_12", resourceName: "Other" },
  ],
  pt: [
    { resourceId: "resource_1", resourceName: "Planejamento de Aula" },
    { resourceId: "resource_2", resourceName: "Guias de Aula" },
    { resourceId: "resource_3", resourceName: "Cartões de Discussão" },
    { resourceId: "resource_4", resourceName: "Perguntas de Avaliação" },
    { resourceId: "resource_5", resourceName: "Tarefas para Alunos" },
    { resourceId: "resource_6", resourceName: "Leituras Relacionadas" },
    { resourceId: "resource_7", resourceName: "Apresentações / Slides" },
    { resourceId: "resource_8", resourceName: "Folhetos" },
    { resourceId: "resource_9", resourceName: "Bibliografia / Referências" },
    { resourceId: "resource_10", resourceName: "Plano de Ensino (Syllabus)" },
    { resourceId: "resource_11", resourceName: "Leituras" },
    { resourceId: "resource_12", resourceName: "Outro" },
  ],
};
