import { Country, Lang } from "@/lib/types/dataTypes";

export const COUNTRIES: Lang<Country> = {
  es: [
    { countryId: "country_1", countryName: "Colombia" },
    { countryId: "country_2", countryName: "Estados Unidos" },
    { countryId: "country_3", countryName: "España" },
    { countryId: "country_4", countryName: "México" },
    { countryId: "country_5", countryName: "El Salvador" },
    { countryId: "country_6", countryName: "Venezuela" },
    { countryId: "country_7", countryName: "Honduras" },
    { countryId: "country_8", countryName: "Ecuador" },
    { countryId: "country_9", countryName: "Chile" },
    { countryId: "country_10", countryName: "Brasil" },
    { countryId: "country_11", countryName: "Uruguay" },
    { countryId: "country_12", countryName: "Paraguay" },
    { countryId: "country_13", countryName: "Perú" },
    { countryId: "country_14", countryName: "Bolivia" },
    { countryId: "country_15", countryName: "Argentina" },
    { countryId: "country_16", countryName: "Nicaragua" },
    { countryId: "country_17", countryName: "Puerto Rico" },
    { countryId: "country_18", countryName: "Panamá" },
    { countryId: "country_19", countryName: "República Dominicana" },
  ],
  en: [
    { countryId: "country_1", countryName: "Colombia" },
    { countryId: "country_2", countryName: "United States" },
    { countryId: "country_3", countryName: "Spain" },
    { countryId: "country_4", countryName: "Mexico" },
    { countryId: "country_5", countryName: "El Salvador" },
    { countryId: "country_6", countryName: "Venezuela" },
    { countryId: "country_7", countryName: "Honduras" },
    { countryId: "country_8", countryName: "Ecuador" },
    { countryId: "country_9", countryName: "Chile" },
    { countryId: "country_10", countryName: "Brazil" },
    { countryId: "country_11", countryName: "Uruguay" },
    { countryId: "country_12", countryName: "Paraguay" },
    { countryId: "country_13", countryName: "Peru" },
    { countryId: "country_14", countryName: "Bolivia" },
    { countryId: "country_15", countryName: "Argentina" },
    { countryId: "country_16", countryName: "Nicaragua" },
    { countryId: "country_17", countryName: "Puerto Rico" },
    { countryId: "country_18", countryName: "Panama" },
    { countryId: "country_19", countryName: "Dominican Republic" },
  ],
  pt: [
    { countryId: "country_1", countryName: "Colômbia" },
    { countryId: "country_2", countryName: "Estados Unidos" },
    { countryId: "country_3", countryName: "Espanha" },
    { countryId: "country_4", countryName: "México" },
    { countryId: "country_5", countryName: "El Salvador" },
    { countryId: "country_6", countryName: "Venezuela" },
    { countryId: "country_7", countryName: "Honduras" },
    { countryId: "country_8", countryName: "Equador" },
    { countryId: "country_9", countryName: "Chile" },
    { countryId: "country_10", countryName: "Brasil" },
    { countryId: "country_11", countryName: "Uruguai" },
    { countryId: "country_12", countryName: "Paraguai" },
    { countryId: "country_13", countryName: "Peru" },
    { countryId: "country_14", countryName: "Bolívia" },
    { countryId: "country_15", countryName: "Argentina" },
    { countryId: "country_16", countryName: "Nicarágua" },
    { countryId: "country_17", countryName: "Porto Rico" },
    { countryId: "country_18", countryName: "Panamá" },
    { countryId: "country_19", countryName: "República Dominicana" },
  ],
};
